# Generated by Django 4.0.2 on 2022-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=10000000000000, unique=True)),
                ('short_url', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
